-- Create USER table
CREATE TABLE "SYSTEM"."USER" (
    "ID" VARCHAR2(100 BYTE) NOT NULL,
    "FIRST_NAME" VARCHAR2(25 BYTE) NOT NULL,
    "LAST_NAME" VARCHAR2(40 BYTE) NOT NULL,
    "EMAIL" VARCHAR2(50 BYTE) NOT NULL,
    "USERNAME" VARCHAR2(45 BYTE) NOT NULL,
    "IS_ADMIN" NUMBER(1,0) NOT NULL,
    "IS_ENABLED" NUMBER(1,0) NOT NULL,
    CONSTRAINT "USER_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "UNQ_EMAIL" UNIQUE ("EMAIL"),
    CONSTRAINT "UNQ_USERNAME" UNIQUE ("USERNAME")
);

-- Create NOTE table
CREATE TABLE "SYSTEM"."NOTE" (
    "ID" VARCHAR2(100 BYTE) NOT NULL,
    "TITLE" VARCHAR2(200 BYTE) NOT NULL,
    "CONTENT" CLOB NOT NULL,
    "DATE_OF_CREATION" TIMESTAMP (6) NOT NULL,
    "DATE_OF_MODIFICATION" TIMESTAMP (6),
    "IS_SHARED" NUMBER(1,0) NOT NULL,
    "ID_USER" VARCHAR2(100 BYTE) NOT NULL,
    CONSTRAINT "NOTE_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "UNQ_TITLE" UNIQUE ("TITLE"),
    CONSTRAINT "FK_NOTE_USER" FOREIGN KEY ("ID_USER") REFERENCES "SYSTEM"."USER" ("ID") ON DELETE CASCADE
);
